version: '3.9'
services:
  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/opeanapi.json'
    volumes:
      - ./test/Functional/data/openapi.json:/tmp/opeanapi.json:ro
    ports:
      - '8080:4010'
